### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xx

### Add to the source dirs
CONTIKI_TARGET_DIRS += launchpad-bp/cc2650

### Include the common launchpad makefile
include $(PLATFORM_ROOT_DIR)/launchpad-bp/Makefile.launchpad-bp
