version: "3"
services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    restart: unless-stopped
    volumes:
      - node_red_data:/data
      - "./settings.js:/data/settings.js"
    ports:
      - "1880:1880"
    networks:
      - localnet
  MQTTbroker:
    container_name: MQTTbroker
    image: eclipse-mosquitto:1.6.13
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      - localnet
#  simulation:
#      build: app
#      restart: unless-stopped

networks:
  localnet:

volumes:
  node_red_data:



